DROP SEQUENCE hibernate_sequence;
CREATE SEQUENCE hibernate_sequence START with 5000;

ALTER TABLE LIEFERUNG ADD CONSTRAINT check_transportart CHECK (TRANSPORT_ART IN ('ST', 'SCH', 'L', 'W'));
ALTER TABLE KUNDE ADD CONSTRAINT check_geschlecht CHECK (GESCHLECHT IN (0, 1));